/*
 * TASK 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * Solution: 4613732
 */
#include "euler.h"

int task2() {
	/*
	 * Simple - just calculate the fibonacci sequence until you hit 4mio
	 */
	long t2 = fib_s(4000000);
	return t2;
}

long t2s = 0;
long fib_s(long n) {
	int first = 0, second = 1, next, c;

	for (c = 0; c < n; c++) {
		if (c <= 1)
			next = c;
		else {
			next = first + second;
			first = second;
			second = next;
		}
		if (next % 2 == 0)
			t2s += next;
		printf("%d\n", next);
		if (next >= 4000000)
			return t2s;
	}
	return t2s;
}
////////////////////////////////////////////////////
// END TASK 2
////////////////////////////////////////////////////
